# -*- coding: utf-8 -*-
"""「StableDiffusionUI_(adapted_to_NovelAILeaks).ipynb」的副本

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R-ZkAJXtMTU6TjD3gMxSDJJ_vZYq8nzK

Clone webui repository
"""

# Commented out IPython magic to ensure Python compatibility.
!git clone https://github.com/AUTOMATIC1111/stable-diffusion-webui
# %cd stable-diffusion-webui

"""Download the model from NovelAILeaks."""

# Commented out IPython magic to ensure Python compatibility.
!mkdir -p /content/stable-diffusion-webui/models/Stable-diffusion /content/stable-diffusion-webui/models/hypernetworks
# %cd /content/stable-diffusion-webui/models/Stable-diffusion/

# 7G animefull-final-latest (may not work)
# !gdown 17WWd6KEsBj7D_0TyGp8aXHQDlchYVs1a -O /content/stable-diffusion-webui/models/Stable-diffusion/model.ckpt

# 4G animefull-final-pruned
# !gdown 1d3f2fvN2gLRocBahZrXe_v1EEHuqpUzT -O /content/stable-diffusion-webui/models/Stable-diffusion/model.ckpt

# 4G animefull-final-pruned (backup)
!curl -Lo model.ckpt https://cloudflare-ipfs.com/ipfs/bafybeicpamreyp2bsocyk3hpxr7ixb2g2rnrequub3j2ahrkdxbvfbvjc4/model.ckpt

# Install VAE Weights (optional)
!curl -Lo model.vae.pt https://cloudflare-ipfs.com/ipfs/bafybeiccldswdd3wvg57jhclcq53lvsc6gizasiblwayvhlv6eq4wow7wu/animevae.pt 

# Install hypernetwork （optional)
!curl -L https://cloudflare-ipfs.com/ipfs/bafybeiduanx2b3mcvxlwr66igcwnpfmk3nc3qgxlpwh6oq6m6pxii3f77e/_modules.tar | tar x -C /content/stable-diffusion-webui/models/hypernetworks

# Install custom embeddings (modified, optional)
# !curl -L https://cloudflare-ipfs.com/ipfs/bafybeie3hdjchxs5tz4n75bos53nhcklslguxchdurc2ynrzcfv2kwyklu/embeddings.tar | tar x -C /content/stable-diffusion-webui/embeddings

"""Launch web ui. You will get a link to nnn.gradio.app, follow it.

Commandline arguments are:
  - `--share` - create online gradio.app link
  - `--gradio-debug` - print outputs to console
  - `--gradio-auth me:qwerty` - add authentication to gradio: username me, password qwerty
"""

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/stable-diffusion-webui
!COMMANDLINE_ARGS="--share --gradio-debug --medvram" REQS_FILE="requirements.txt" python launch.py

"""commands for ***after*** you have gotten done with a session
============================================================================

Zip images for downloading on local drive (click the folder icon on the left, the one below {x})
"""

!zip -r /content/stable-diffusion-webui /content/stable-diffusion-webui/outputs

"""Save images to Google Drive **Warning: this will cause google to scan your drive, so if you intend to use this and worry about that kind of stuff, probablly just set this up on a clean account that's just for this colab**"""

from google.colab import drive # type: ignore

try:
   drive_path = "/content/drive"
   drive.mount(drive_path,force_remount=False)
except:
   print("...error mounting drive or with drive path variables")

!cp -r "/content/stable-diffusion-webui/outputs" "/content/drive/MyDrive"